### PR TITLE
Changes generated by publish script

### PR DESCRIPTION
**Pull request by caesarxuchao**
In the first commit I manually removed the filter-branch-sha. I also rewrote kubernets-sha: it used to records the last commit of k8s.io/kubernetes when the sync script is called, now it records the last commit of k8s.io/kubernetes ***that affects staging/src/k8s.io/apimachinery*** when the sync script is called.

Ref:
https://github.com/kubernetes/client-go/pull/140 is the changes generated for client-go in the same run of the scripts.

cc @sttts

### CODE REVIEW

**Comment by deads2k** [comment]
These changes don't seem to match what you'd get from: https://github.com/kubernetes/apimachinery/blob/master/hack/godep-deps.sh .  The commits aren't named the same way and the names "Update vendor/" aren't following an obvious pattern.

About the removal of `filter-branch-sha`.  You're somehow determining what that value would have been based on the kube commit?  I think its here: https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/publish_scripts/util.sh#L49 , but I really have no idea how it works.

Since you're trying to remove the sync scripts from the individual repos, can you add synchronization for apiserver, sample-server, and kube-aggregator to make sure the generic script you're providing for synchronization is generic?

**Comment by caesarxuchao** [comment]
> These changes don't seem to match what you'd get from: https://github.com/kubernetes/apimachinery/blob/master/hack/godep-deps.sh . The commits aren't named the same way and the names "Update vendor/" aren't following an obvious pattern.

Surely i can update the commit message to match the convention. I ran hack/godep-deps.sh and it just added some `"Comment": "v1.2-96-g09691a3",` to the Godep.json. And the generated "Update vendor/" commit removed the glog, which is on purpose, and pulled in some LICENSE and CONTRIBUTORS files. Did you see other differences?

**Comment by caesarxuchao** [comment]
> About the removal of filter-branch-sha. You're somehow determining what that value would have been based on the kube commit? I think its here: https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/publish_scripts/util.sh#L49 , but I really have no idea how it works.

Yeah, the script adds the original kubernetes-SHA to commit messgae when filter-branching, so no need to keep a separate filter-branch-SHA anymore.

**Comment by caesarxuchao** [comment]
> Since you're trying to remove the sync scripts from the individual repos, can you add synchronization for apiserver, sample-server, and kube-aggregator to make sure the generic script you're providing for synchronization is generic?

Doing this now.

**Comment by sttts** [comment]
LICENSE, CONTRIBUTORS, AUTHORS is due to newer godeps.

From my side lgtm, @caesarxuchao feel free to merge when you need to.

**Comment by deads2k** [comment]
> Surely i can update the commit message to match the convention.

That would work.



> Doing this now.

Thanks.

**Comment by pmorie** [comment]
I'd really like this to be sorted out ASAP.  We need to be able to consume API changes via client-go that haven't propagated out yet due to the publication breakage.

**Comment by deads2k** [comment]
@caesarxuchao Is the automated script close to being worked out.  People can't rebase onto a coherent level until we sync.  Do we need another manual sync?

**Comment by deads2k** [comment]
I'd merge this to get the auto-publishing working.  Let me know if/when you're ready.

**Comment by aveshagarwal** [comment]
@caesarxuchao  I am rebasing kubernetes-incubator/cluster capacity to kube 1.6. And I think I have hit an issue with vendoring k8s.io/apimachinery. k8s.io/apimachinery is not up-to-date with k8s.io/kubernetes/staging/src/k8s.io/apimachenry and due to this compilation is failing like:

vendor/k8s.io/kubernetes/pkg/api/helpers.go:247: undefined: v1.FinalizerOrphanDependents

**Comment by sttts** [comment]
@aveshagarwal sync is not active yet. Give @caesarxuchao some hours. We are getting near.

**Comment by caesarxuchao** [comment]
@deads2k we can merge this pull and https://github.com/kubernetes/client-go/pull/140 if users need it urgently.

This pull has a minor issue that the message of the commit updating vendor is not following a convention. Also k8s.io/apiserver, k8s.io/kube-aggregator, k8s.io/sampe-apisever will be out of sync, hopefully i can submit PRs for them today.

I'm tuning the performance of the robot, currently it's taking more than an hour to run, so tuning it will also take some time.

**Comment by sttts** [comment]
> I'm tuning the performance of the robot, currently it's taking more than an hour to run, so tuning it will also take some time.

Multiple godep runs?

**Comment by caesarxuchao** [comment]
No, multiple `git fetch` of kubernetes. Can i maintain a local k8s.io/kubernetes and let other repos fetch it? This will also make sure each repo is publishing the same version of k8s.io/kubernetes.

**Comment by deads2k** [comment]
> I'm tuning the performance of the robot, currently it's taking more than an hour to run, so tuning it will also take some time.

Do we care?  I mean, sure it could/should be better, but is the a reason to avoid turning it on now and making it faster later?

**Comment by caesarxuchao** [comment]
If a PR that changes staging/ gets merged during one run of publishing robot, we end up syncing different versions of kubernetes for different repos.

Making the publishing process faster will reduce the risk (this is what i'm doing now). If we can `git fetch` kubernetes locally we can completely remove the risk.

**Comment by caesarxuchao** [comment]
Also it's very hard to debug now, I'm trying to enable the robot for all repos as @deads2k suggested, I had minor bug in my scripts, but it took hours to rerun..

**Comment by sttts** [comment]
> Can i maintain a local k8s.io/kubernetes and let other repos fetch it? This will also make sure each repo is publishing the same version of k8s.io/kubernetes.

Make one checkout and do a `git clone --reference the-global-checkout`.

**Comment by caesarxuchao** [comment]
Actually we can fetch locally: http://stackoverflow.com/questions/4131164/how-do-i-pull-from-another-computers-repository-in-git

I tried locally and it works. I guess i'll have to fight with some ssh permission issues but in general we are good.

**Comment by caesarxuchao** [comment]
k8s.io/apiserver does not compile without flatten its vendor and k8s.io/apimachinery's vendor:
```
# k8s.io/apiserver/pkg/server/openapi
./openapi.go:56: cannot use config.Info (type *"k8s.io/apimachinery/vendor/github.com/go-openapi/spec".Info) as type *"k8s.io/apiserver/vendor/github.com/go-openapi/spec".Info in field value
```
The failure is because apiserver depends on apimachinery, and they both import github.com/go-openapi, so there are two copies of that github.com/go-openapi.

**Comment by caesarxuchao** [comment]
Newly generated changes to all 5 repos:
https://github.com/kubernetes/client-go/pull/140
https://github.com/kubernetes/apimachinery/pull/10
https://github.com/kubernetes/apiserver/pull/4
https://github.com/kubernetes/kube-aggregator/pull/4
https://github.com/kubernetes/sample-apiserver/pull/2

@sttts @deads2k could you help take a look at them? The client-go ones have been reviewed by Mehdy already.

I had downloaded the code locally, after I removed flatten the vendor/ in apiserver, apimachinery, kube-aggregator, and sample apiserver, they all build. They don't build without the flattening because this [issue](https://github.com/kubernetes/apimachinery/pull/9#issuecomment-287569299).

client-go can build without flatten its vendor/, but that's just luck.

**Comment by deads2k** [comment]
Your sync script needs to checkout the previous godeps.json (before the last sync) in order to apply the commits from k8s.io/kubernetes.  It looks like you did it once manually in the commit history.  Other than that, they look good.

**Comment by caesarxuchao** [comment]
@deads2k godeps.json is checked out. I didn't do that manually, the only manual change i did was changing the sha in the metadata. Also, please take a look at #10. That's the latest changes I generated over the weekend.

**Pull request closed without merging**
