### PR TITLE
Fix strategicpatch swallowed errors

### PR DESCRIPTION
**Pull request by alrs**
There are four dropped error variables in the strategicpatch package.

### CODE REVIEW

**Comment by alrs** [comment]
I'm looking for a reviewer, so I'm going to @ all of the reviewers in the OWNERS file. Is there a better process for this? @thockin @lavalamp @smarterclayton @wojek-t @deads2k @derekwaynecarr @caesarxuchao @makedanese @liggitt @gmarek @stts @ncdc @tallclair

**Comment by alrs** [comment]
typo'd @wojtek-t and @mikedanese above ^

**Comment by ncdc** [comment]
@alrs thanks for the PR! This repo, however, is currently sourced from the code in the https://github.com/kubernetes/kubernetes/ repo, in the staging dir. I'd recommend you open a PR there instead (see https://github.com/kubernetes/apimachinery/blob/master/README.md for more details).

**Comment by alrs** [comment]
Thanks, @ncdc

**Pull request closed without merging**
