### PR TITLE
Generated by robot

### PR DESCRIPTION
**Pull request by caesarxuchao**
All 5 PRs generated in the same run of the robot:
https://github.com/kubernetes/client-go/pull/140
https://github.com/kubernetes/apimachinery/pull/10
https://github.com/kubernetes/apiserver/pull/4
https://github.com/kubernetes/kube-aggregator/pull/4
https://github.com/kubernetes/sample-apiserver/pull/2

### CODE REVIEW

**Comment by sttts** [comment]
@caesarxuchao Is the Godeps.json update with removed glog missing here?

**Comment by deads2k** [comment]
lgtm

**Comment by deads2k** [comment]
> @caesarxuchao Is the Godeps.json update with removed glog missing here?

He stripped the vendored copy because of the init work (flag registration I think) in glog.

**Comment by caesarxuchao** [comment]
glog still exists in Godeps, i just removed it from vendor/, to avoid duplicate flag registration if there is another glog in the GOPATH.
I can remove glog from vendor/ because glog is quite stable, and the head of its master works.

**Comment by deads2k** [comment]
merging in preparation for turning on the auto-sync scripts

**Pull request merged**
